#############################################################################
# Makefile for building: ProjetoTP1_EXEC
# Generated by qmake (2.01a) (Qt 4.8.7) on: qui jun 22 16:18:34 2017
# Project:  ProjetoTP1.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ProjetoTP1.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/local/include/opencv -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_video -lopencv_photo -lopencv_flann -lopencv_face -lopencv_objdetect -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_ml -lopencv_imgproc -lopencv_core -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		janela.cpp \
		novousuario.cpp \
		lerface.cpp \
		pessoa.cpp \
		reserva.cpp \
		novareserva.cpp \
		listareservas.cpp moc_janela.cpp \
		moc_novousuario.cpp \
		moc_lerface.cpp \
		moc_novareserva.cpp \
		moc_listareservas.cpp
OBJECTS       = main.o \
		janela.o \
		novousuario.o \
		lerface.o \
		pessoa.o \
		reserva.o \
		novareserva.o \
		listareservas.o \
		moc_janela.o \
		moc_novousuario.o \
		moc_lerface.o \
		moc_novareserva.o \
		moc_listareservas.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ProjetoTP1.pro
QMAKE_TARGET  = ProjetoTP1_EXEC
DESTDIR       = 
TARGET        = ProjetoTP1_EXEC

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_janela.h ui_novousuario.h ui_novareserva.h ui_listareservas.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ProjetoTP1.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ProjetoTP1.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ProjetoTP1.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ProjetoTP1_EXEC1.0.0 || $(MKDIR) .tmp/ProjetoTP1_EXEC1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ProjetoTP1_EXEC1.0.0/ && $(COPY_FILE) --parents janela.h novousuario.h lerface.h pessoa.h reserva.h novareserva.h listareservas.h .tmp/ProjetoTP1_EXEC1.0.0/ && $(COPY_FILE) --parents main.cpp janela.cpp novousuario.cpp lerface.cpp pessoa.cpp reserva.cpp novareserva.cpp listareservas.cpp .tmp/ProjetoTP1_EXEC1.0.0/ && $(COPY_FILE) --parents janela.ui novousuario.ui novareserva.ui listareservas.ui .tmp/ProjetoTP1_EXEC1.0.0/ && (cd `dirname .tmp/ProjetoTP1_EXEC1.0.0` && $(TAR) ProjetoTP1_EXEC1.0.0.tar ProjetoTP1_EXEC1.0.0 && $(COMPRESS) ProjetoTP1_EXEC1.0.0.tar) && $(MOVE) `dirname .tmp/ProjetoTP1_EXEC1.0.0`/ProjetoTP1_EXEC1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ProjetoTP1_EXEC1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_janela.cpp moc_novousuario.cpp moc_lerface.cpp moc_novareserva.cpp moc_listareservas.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_janela.cpp moc_novousuario.cpp moc_lerface.cpp moc_novareserva.cpp moc_listareservas.cpp
moc_janela.cpp: lerface.h \
		pessoa.h \
		novousuario.h \
		novareserva.h \
		reserva.h \
		listareservas.h \
		janela.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) janela.h -o moc_janela.cpp

moc_novousuario.cpp: pessoa.h \
		lerface.h \
		novousuario.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) novousuario.h -o moc_novousuario.cpp

moc_lerface.cpp: pessoa.h \
		lerface.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) lerface.h -o moc_lerface.cpp

moc_novareserva.cpp: reserva.h \
		pessoa.h \
		novareserva.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) novareserva.h -o moc_novareserva.cpp

moc_listareservas.cpp: reserva.h \
		pessoa.h \
		listareservas.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) listareservas.h -o moc_listareservas.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_janela.h ui_novousuario.h ui_novareserva.h ui_listareservas.h
compiler_uic_clean:
	-$(DEL_FILE) ui_janela.h ui_novousuario.h ui_novareserva.h ui_listareservas.h
ui_janela.h: janela.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic janela.ui -o ui_janela.h

ui_novousuario.h: novousuario.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic novousuario.ui -o ui_novousuario.h

ui_novareserva.h: novareserva.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic novareserva.ui -o ui_novareserva.h

ui_listareservas.h: listareservas.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic listareservas.ui -o ui_listareservas.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp janela.h \
		lerface.h \
		pessoa.h \
		novousuario.h \
		novareserva.h \
		reserva.h \
		listareservas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

janela.o: janela.cpp janela.h \
		lerface.h \
		pessoa.h \
		novousuario.h \
		novareserva.h \
		reserva.h \
		listareservas.h \
		ui_janela.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o janela.o janela.cpp

novousuario.o: novousuario.cpp novousuario.h \
		pessoa.h \
		lerface.h \
		ui_novousuario.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o novousuario.o novousuario.cpp

lerface.o: lerface.cpp lerface.h \
		pessoa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lerface.o lerface.cpp

pessoa.o: pessoa.cpp pessoa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pessoa.o pessoa.cpp

reserva.o: reserva.cpp reserva.h \
		pessoa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reserva.o reserva.cpp

novareserva.o: novareserva.cpp novareserva.h \
		reserva.h \
		pessoa.h \
		ui_novareserva.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o novareserva.o novareserva.cpp

listareservas.o: listareservas.cpp listareservas.h \
		reserva.h \
		pessoa.h \
		ui_listareservas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o listareservas.o listareservas.cpp

moc_janela.o: moc_janela.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_janela.o moc_janela.cpp

moc_novousuario.o: moc_novousuario.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_novousuario.o moc_novousuario.cpp

moc_lerface.o: moc_lerface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lerface.o moc_lerface.cpp

moc_novareserva.o: moc_novareserva.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_novareserva.o moc_novareserva.cpp

moc_listareservas.o: moc_listareservas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_listareservas.o moc_listareservas.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

